# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'fab fa-discord', link: 'https://discord.gg/KvFxPuheDH'}
- {icon: 'fab fa-linkedin', link: 'https://www.linkedin.com/in/jan-vincent-nowak/'}
- {icon: 'fab fa-youtube', link: 'https://www.youtube.com/user/ZypZockt'}
- {icon: 'fab fa-github', link: 'https://github.com/janvincentnowak'}
- {icon: 'fas fa-cubes', link: 'https://www.instagram.com/'}
- {icon: 'fas fa-envelope', link: 'mailto:j.v.nowak@gmx.de'}
# - {icon: 'fas fa-rss-square', link: '/feed.xml'}

# Customize site text
pagination:w
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'